### ISSUE TITLE
support polymorphism ?

### ISSUE THREAD

**Issue by amir-arad** [colyseus/schema#11]
my game model has an inheritance tree (`Asteroid` and `SpaceShip` both inheriting from `SpaceObject`), and I want to have a map of all objects in the room state(`@type({map: SpaceObject})`). 
It would be nice if Inheritance limitations were documented (after all, there are some `// support inheritance` comments in the code).

**Comment by amir-arad** [comment]
I see now the `Items inside Arrays and Maps must be all of the same type` limitation in the readme. my bad :)

**Comment by endel** [comment]
So many people are requesting this, I'll leave this open until we actually implement it!

This can be supported if - when encoding a child `Schema` type that differs from the one provided by the definition - we include additional bytes ("other type" + "type id") to define which type that object is. Then we can identify it during decoding. Not trivial to implement but totally possible

**Comment by amir-arad** [comment]
Is it possible to extract a "contract" for Schema type + instance? this way It's so much easier to play with other approaches.

**Comment by endel** [comment]
@amir-arad not sure if that's what you're asking for, but you can access the definitions from any `Schema` instance through `instance.constructor. _schema`

**Comment by amir-arad** [comment]
@endel I mean, If I want to write my own type implementation, what would I need to implement? I can see the API from the Schema type definition, but if there was a contract definition i could consult, that would be nice.

**Comment by endel** [comment]
@amir-arad I see! all the primitive types are [hardcoded](https://github.com/colyseus/schema/blob/5f7561a7d8dd3aeab0d98f56f817120abc3aede9/src/annotations.ts#L14-L30) currently. you'd like to instead of using `@type("float32")` use `@type("custom_thing")` instead?

for that would need to expose an api on both encoder and decoders

**Comment by amir-arad** [comment]
something like that. how about `@type(CustomThing)`?
this way I don't need to register what `"custom_thing"` means.
I'd expect `CustomThing` to have encode / decode/ watch functions, for full or patch data. does the object have to be of type Schema?

**Comment by endel** [comment]
hey @amir-arad, sorry the delay to reply.

Currently it's not really possible to implement your own encode/decode methods in JavaScript, because the actual implementation is not used in the client-side. The schema definitions are passed from the server to the client using `Reflection.encode()`, which will not include a custom `decode` method.

This should be achieavable using the C# client though, as the C# code for the schema needs to be generated and compiled.

In C#, you join a room using `client.join<State>(roomName)`, and the `State` implementation is instantiated through the Generic argument. The same is not possible in TypeScript, as generics are not part of the runtime. It could be an option to provide the actual implementation differently in JavaScript/Typescript, maybe as a third argument?

Cheers
