### ISSUE TITLE
Re-using the same instance on multiple fields / .clone() automatically?

### ISSUE THREAD

**Issue by endel** [colyseus/schema#54]
It's currently not possible to re-use the same `Schema` instance to be encoded on multiple fields, as whenever it is encoded once, all changes are going to be discarded for the next field.

Approaches that can be taken internally to improve this:
- Clone the instance automatically whenever it's assigned for the second time (easiest route)
- Track the instance internally, and actually re-use the same instance during decoding time (more complicated)

**Comment by amir-arad** [comment]
Some solutions to this problem may also enable an object to be exposed in more than one room. That would be preferable for large scale games, with different scopes.

**Comment by rnd256** [comment]
I think "Clone the instance automatically whenever it's assigned for the second time" would cause issues when developers keep around a reference to the original object and don't realize that it's no longer linked to the cloned object.

If it turns out that it's not particularly feasible to resolve this issue, then IMO the next best thing would be to throw an error when it's encountered server-side (I hit this issue a while back and it was very difficult to debug).

**Comment by endel** [comment]
Thanks for the feedback @rnd256. With the restructuring of ChangeTree's that's going on https://github.com/colyseus/schema/issues/75 it should be possible to implement instance-sharing during decoding time - at any levels of the structure (direct references, items of arrays and maps)

Things are not quite stable yet, hopefully they will in a few weeks. 🙏

**Comment by endel** [comment]
Version 0.14 landed and when the same instance is used multiple times, only the `refId` of that instance is synchronized!
