### ISSUE TITLE
@filter: how to approach it?

### ISSUE THREAD

**Issue by endel** [colyseus/schema#61]
I've been thinking about how to approach the `@filter()` for better performance.

Internally, `@colyseus/schema` uses a simple array of numbers (`number[]`) to encode the full state. This array of numbers is turned into a `Buffer` to be sent over the wire via WebSockets.

To avoid re-encoding every structure again for each client, here's my proposal:

- Encode the full state once:
  - Cache the index where each structure starts and ends within the `.$changes` property (`$changes` can be renamed to `$cache`)
  - Turn the full encoded state into a `Buffer`
- For each client:
  - Iterate through all `@filter()` in the structures
    - Retrieve index where filtered values are positioned at
    - Use `Buffer.slice()` to retrieve the portions of the state the client is going to receive
  - Use `Buffer.concat()` to combine all sliced portions.
  - Send it!

I've done some benchmarks and using `Buffer.slice()` + `Buffer.concat()` consumes way less CPU than operating through the `number[]` arrays and then turning them into a `Buffer`.

**Comment by oyed** [comment]
This is a follow-up to a suggestion in Discord.

I have not tested this (yet), it's just a random thought and I have no idea if the GC overhead or actual performance is better than your suggestion @endel 

The `number[]` array used for state updates over the WebSockets - instead of splicing this array with filter calls, might performance be improved by instead doing a `.join(',')` on the array, then using `.slice(index, length)` on the resulting string for filter calls, before `.split(',')` for sending to the client more performant?

Again, I have no idea on the ramifications of this on GC, or whether it improves performance what-so-ever (Only benefit I see is if V8 has to recalculate indexes when filtering the original array - if it doesn't, this likely won't improve anything), I'll see about writing a perf test ASAP if you're too busy.

**Comment by endel** [comment]
I see, thanks for the suggestion @oyed, I mentioned operating directly in the `Buffer` because creating them seems to be very expensive. So would need to check how costly it is for creating new `Buffer`'s to send for each client.

**Comment by oyed** [comment]
I assume we'd be creating a new buffer per client regardless of the method (In terms of memory), since we'd be duplicating the Buffer to filter it - maybe duplicating the string (Since the length would probably be pretty big) _and_ the Buffer would be enough to make this less performant, who knows - I'll see about writing a perf to check

**Comment by endel** [comment]
Version 0.14 has been released with `@filter()` and `@filterChildren()` 🎉 
 https://github.com/colyseus/colyseus/releases/tag/0.14.0
