### ISSUE TITLE
MapSchema onRemove issue

### ISSUE THREAD

**Issue by kasparsj** [colyseus/schema#71]
Hi guys!
Here I was trying to remove the old player, when a new tab is opened:
```typescript
    onAuth(client, options, req) {
        if (req.sessionID) {
            if (this.state.sessions[req.sessionID]) {
                this.state.removePlayer(this.state.sessions[req.sessionID]);
            }
            this.state.sessions[req.sessionID] = client.sessionId;
            return true;
        }
        return false;
    }

    onJoin(client, options) {
        super.onJoin(client, options);
        this.state.createPlayer(client.sessionId);
    }
```
it works on the server side, but on the client side:

- in the old tab it correctly removes the user

- in the new tab it adds a new user, and straight away removes it

Looking at the code here (https://github.com/colyseus/schema/blob/master/src/Schema.ts#L294):
I guess this is because it takes the newly added player's index.

**Comment by endel** [comment]
Hi @kasparsj, 

Thanks for taking the time to report this.

There is a known issue that you can't REMOVE and CREATE the same attribute at the same patch. I suggest trying to come up with a workaround while this is not solved.

**Comment by kasparsj** [comment]
OK, thanks for quick reply!

**Comment by damian-pastorini** [comment]
Hi @endel , checking the planned changes I saw this issue and I would like to mention that I had the same case, but I'm 100% sure it was working in previous versions. I'm on 0.12 and it's already happening, so it has to be something on 0.11 (more likely) or 0.10 because I've got this working on 0.9 for sure. If I can find the time I will check on which version exactly (if 0.11 or 10) this broke up so you may have an idea on what changed that could make this happen.

**Comment by damian-pastorini** [comment]
Hi @endel I didn't have time to test it but after take a look on the versions this was working on my app in my last version 3 which had Colyseus 0.12.4, hope this helps.

**Comment by endel** [comment]
Version 0.14 should fix this! 🎉 
 https://github.com/colyseus/colyseus/releases/tag/0.14.0
