### ISSUE TITLE
Remove `| any` from MapSchema values

### ISSUE THREAD

**Issue by JoaoMosmann** [colyseus/schema#77]
I wonder what is the reason of the `| any` type for the keys of a MapSchema.
As the docs state, all values of a MapSchema should be of the same type. So there is no reason for having another type than `T`

https://github.com/colyseus/schema/blob/098f3dc2663da478a76c98a4f1aadbfed84923bc/src/types/MapSchema.ts#L86

**Comment by endel** [comment]
Hi @JoaoMosmann, glad to see you here again :) 

As the `MapSchema` defines methods **and** has a list of properties attached to itself, the `T | any` is supposed to hold both the methods and the properties attached to it. The problem is that `any` is eager and everything is then treated as `any`.

I'm working on a fix along with a bunch of other issues here https://github.com/colyseus/schema/issues/75 

Here's how the new version will look like so far: https://github.com/colyseus/schema/blob/8e6ef6419168f238b53b134992450661f240db74/src/types/MapSchema.ts#L9
